version: '3.8'

services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: pgadmin
    restart: always
    env_file: .env
    volumes:
      - local_pgadmin_data:/var/lib/pgadmin
    ports:
      - 5433:80
    depends_on:
      - postgres

  backend:
    container_name: spi_backend
    restart: always
    build:
      context: .
      dockerfile: ./compose/nodejs/Dockerfile
      args:
        - APP_ENVIRONMENT=production
        - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-postgres}?schema=public
    # ports:
    #   - '${PORT:-3000}:3000'
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    # image: nginx:alpine
    build:
      context: ./compose/nginx
      dockerfile: Dockerfile
    container_name: spi_nginx
    restart: always
    ports:
      - '${PORT:-3000}:443'
    # volumes:
    #   - ./compose/nginx/nginx_config.conf:/etc/nginx/conf.d/spi_backend.conf:ro
    # volumes:
    # - ./certs:/etc/nginx/certs:ro
    # - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  local_postgres_data:
  local_pgadmin_data:
