export type TOutputConsolidated = {
  courseCode: string;
  courseName: string;
  section: string;
  initial: number | null;
  final: number;
  APB: number;
  RPB: number;
  NSP: number;
  ABD: number;
  teacherCode: string;
  teacherName: string;
  department: string;
  modality: string;
  indexAPB: number | null;
  indexRPB: number | null;
  indexNSP: number | null;
  indexABD: number | null;
  finalSummatoryInconsistency: 'Error' | 'Correcto';
  initialSummatoryInconsistency: 'Correcto' | 'Incorrecto' | null;
  terminalEfficiency: number | null;
  pac: number;
  year: number;
};
